### ISSUE TITLE
derpfest kanged or wot lmao 

### ISSUE THREAD

**Issue by ossfapper360** [DerpFest-12/frameworks_base#7]
pls hide it

**Comment by NurKeinNeid** [comment]
No, I guess you misunderstand. This is not crdroid. 

There you can find the kanged copy of our source:
https://github.com/crdroidandroid

**Comment by ossfapper360** [comment]
> No, I guess you misunderstand. This is not crdroid.
> 
> There you can find the kanged copy of our source: https://github.com/crdroidandroid

https://github.com/crdroidandroid/android_frameworks_base/commits?author=NurKeinNeid
bruh help me find

**Comment by NurKeinNeid** [comment]
You're searching it wrong

Here one example:
https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/5491d624c1c9f6ee5d33c165698eb9f7b9178979#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cL2

**Comment by ossfapper360** [comment]
> You're searching it wrong
> 
> Here one example: [crdroidandroid/android_packages_apps_GameSpace@5491d62#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cL2](https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/5491d624c1c9f6ee5d33c165698eb9f7b9178979#diff-b8612be0ca7904aab0cafe581788e1b998893c4b681fdd0e1ea329168cc3938cL2)

at least he did that while being oss and corrected his mistake u egoist rart

**Comment by ossfapper360** [comment]
also chaldeaprjkt != derpfest ig?

**Comment by NurKeinNeid** [comment]
Yes, he was contributing to DerpFest. Maybe you can't imagine but sometimes ROMs are made from more then one guy.

**Comment by NurKeinNeid** [comment]
Excuses over excuses lol, you're obviously a troll who don't know shit
